parameters:
    urodoz_translation_manager.class: Urodoz\Bundle\TranslationUnitBundle\Service\LocaleManager

services:
    urodoz.translation_manager:
        class: %urodoz_translation_manager.class%
        calls:
            - [setContainer, [@service_container]]
